### ISSUE TITLE
Missing docker file picameleon

### ISSUE THREAD

**Issue by gabeale** [Esser50K/PiCameleon#10]
Hi,
I have tried to install PiCameleon through docker following the installation guidelines (ref. https://github.com/Esser50K/PiCameleon ) but docker file is not available.
Can you please have a look?
Thx

**Comment by gabeale** [comment]
Please find attached the error snap-shot.
![PiCameleon](https://user-images.githubusercontent.com/41168339/127001628-c4e77fa5-2be6-4faa-904a-4f180993221c.PNG)

Thx

**Comment by gabeale** [comment]
Dear friend,
Any news so far?
Thx in advance

**Comment by Esser50K** [comment]
oh sorry I was not paying attention to this. You need to build the image first, I didn't publish it on dockerhub.

So you need to run this in the root folder:
```
docker build -t picameleon:latest .
```

**Comment by Esser50K** [comment]
I added the necessary documentation on the README.md, closing the issue for now
